name: "Whiskers Check"

# Run on any update to an open pull request
on:
  pull_request:

jobs:
  whiskers-check:
    runs-on: ubuntu-latest

    steps:
      - name: "Install Whiskers"
      # Ideally this would pull the latest whiskers version
      - run: |
          curl -fsSL https://github.com/catppuccin/toolbox/releases/download/whiskers-v2.2.0/whiskers-x86_64-unknown-linux-gnu -o $RUNNER_TEMP/whiskers
          chmod +x $RUNNER_TEMP/whiskers
          echo $RUNNER_TEMP >> $GITHUB_PATH

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Check"
      - run: whiskers sublime-color-scheme.tera --check



